apiVersion: v1
kind: Secret
metadata:
  name: specheal-secrets
  namespace: merge-kalau-berani
type: Opaque
stringData:
  DATABASE_URL: postgresql://merge_kalau_berani:replace-db-password@103.185.52.138:1185/merge_kalau_berani
  POSTGRES_USER: merge_kalau_berani
  POSTGRES_PASSWORD: replace-db-password
  POSTGRES_DB: merge_kalau_berani
  OPENAI_API_KEY: replace-me
  OPENAI_MODEL: gpt-4o-mini
  NEXT_PUBLIC_BASE_URL: https://merge-kalau-berani.hackathon.sev-2.com
  PLAYWRIGHT_HEADLESS: "true"
  JIRA_SITE_URL: https://specheal.atlassian.net
  JIRA_USER_EMAIL: argaadolflumunon@gmail.com
  JIRA_API_TOKEN: replace-me
  JIRA_PROJECT_KEY: SH
  JIRA_TASK_ISSUE_TYPE: Task
  JIRA_BUG_ISSUE_TYPE: Bug
